### ISSUE TITLE
Trait not found

### ISSUE THREAD

**Issue by RandomStrangerOnTheInternet** [Fanmade/laravel-bitwise-trait#1]
Hello, I have just installed the package using composer (as mentioned in the `README.md`)

And I receive the following error:
![image](https://user-images.githubusercontent.com/47994830/63654695-3c1f4600-c77e-11e9-93a4-0f16d055f58a.png)

I have also done a `composer dump-autoload` but that made no difference
Version: `Laravel Framework 5.8.33`

It would be appreciated if you have some time in order to help me resolve this issue, I'm fairly convinced it's an issue on my end because I'm not that experienced with Laravel

**Comment by Fanmade** [comment]
Hi @RandomStrangerOnTheInternet ,
sorry for the late reply, just saw your question now.
Your import namespace is wrong. You need to use `use Fanmade\Bitwise\BitwiseFlagTrait;` instead of `use App\Traits\BitwiseFlagTrait`, or the autoloader can't find the file.

I just saw that you used exactly the namespace I used in the readme, so I updated that. The code examples where from my project in which I initially wrote the trait, so that's why it was within 'app\Traits' there. 
Please let me know if it works now :)

**Comment by RandomStrangerOnTheInternet** [comment]
That does the job, thanks!
